version: '3.9'

services:
  tomcat:
    image: tomcat:10.1
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/rent-web-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/rent-web.war
    command: >
      /bin/bash -c "apt-get update && apt-get install -y unzip
      && unzip -o /usr/local/tomcat/webapps/rent-web.war -d /usr/local/tomcat/webapps/rent-web
      && catalina.sh run"
